[build]
  command = "npm ci && npm run build"
  publish = "dist"

[[redirects]]
  from = "/app-ads.txt"
  to = "/.netlify/functions/app-ads.txt"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
